requirements: add setuptools
From a fresh installation of Ubuntu 24.04 with build-essential there
was an error when following the build instructions in the readme.

```
ModuleNotFoundError: No module named 'pkg_resources'
```

This was due to a missing `setuptools` package.

Add `setuptools` to `requirements.txt`.

Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>